changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        - breaking
    - title: New Features 🎉
      labels:
        - enhancement
        - feature
        - integration
    - title: Bug Fixes 🐛
      labels:
        - bug
        - fix
    - title: Documentation 📚
      labels:
        - documentation
        - docs
        - example
        - examples
